name: Common Test

on:
  workflow_dispatch:
  push:
    branches: [master, "avoid_234"]
    tags: ["*"]

jobs:

  build_and_test:
    name: Build and Test on Erlang/OTP ${{matrix.otp}} | Rebar3 ${{matrix.rebar3}} | Rust ${{matrix.rust}}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        otp: ['26.2.2']
        # elixir: ['1.16.1']
        rebar3: ['3.22.1']
        rust: ['1.76.0']
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends build-essential cmake liblz4-dev libncurses-dev libsnappy-dev libssl-dev liburing-dev liburing2 openssl pkg-config bash curl git tar

      - name: Install Rust ${{matrix.rust}} toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: rustler
          save-if: false

      - name: Install OTP Rebar3
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          # elixir-version: ${{matrix.elixir}}
          rebar3-version: ${{matrix.rebar3}}

      - name: Start epmd
        run: epmd -daemon

      - name: Build and Test cozodb
        run: make test

